blank_issues_enabled: false
contact_links:
  - name: Documentation Suggestion
    url: https://github.com/primary-theme/primary-theme.github.io/issues
    about: Want to suggest an improvement to the documentation site? Please report here instead!
  - name: Primary Theme Guide
    url: https://primary-theme.github.io/
    about: View the complete list of features, how to use them, guides and more.